// Marketplace demo data — mock only, not backed by Supabase yet.
// Shape consumed by CommerceCard / CommerceSearchPage / CommerceSavedPage

export const commerceCategories = ["All", "Electronics", "Fashion", "Home", "Vehicles", "Services"];

export const demoProducts = [
  {
    id: "prod-1",
    title: "Starlink Standard Kit (Gen 3)",
    category: "Electronics",
    type: "Electronics",
    price: 450,
    currency: "$",
    condition: "New",
    seller: "Tariro M.",
    initials: "TM",
    location: "Borrowdale, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-1/500/375",
    verified: true,
    postedAt: "20m ago",
    description: "Brand new sealed kit. Includes router, dish, cables + 30 days free data. Installation available.",
  },
  {
    id: "prod-2",
    title: "MacBook Air M1 2020 - 8GB / 256GB",
    category: "Electronics",
    type: "Electronics",
    price: 550,
    currency: "$",
    condition: "Used - excellent",
    seller: "Tinashe D.",
    initials: "TD",
    location: "Avondale, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-2/500/375",
    verified: true,
    postedAt: "1h ago",
    description: "Battery cycles 89, clean screen, with original charger. Ideal for dev / uni.",
  },
  {
    id: "prod-3",
    title: "Samsung 55\" QLED 4K TV",
    category: "Electronics",
    type: "Electronics",
    price: 380,
    currency: "$",
    condition: "Used - good",
    seller: "Vimbai S.",
    initials: "VS",
    location: "Mount Pleasant, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-3/500/375",
    verified: true,
    postedAt: "3h ago",
    description: "No lines, remote + wall bracket included. Selling due to relocation.",
  },
  {
    id: "prod-4",
    title: "iPhone 13 Pro 128GB - Sierra Blue",
    category: "Electronics",
    type: "Electronics",
    price: 420,
    currency: "$",
    condition: "Used - excellent",
    seller: "Anesu K.",
    initials: "AK",
    location: "Newlands, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-4/500/375",
    verified: true,
    postedAt: "5h ago",
    description: "BH 88%, no cracks, Face ID works. Box + case included.",
  },
  {
    id: "prod-5",
    title: "Toyota Aqua 2017 Hybrid",
    category: "Vehicles",
    type: "Vehicles",
    price: 7600,
    currency: "$",
    condition: "Used",
    seller: "Farai N.",
    initials: "FN",
    location: "Msasa, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-5/500/375",
    verified: true,
    postedAt: "2h ago",
    description: "Duty paid, 92k km, hybrid battery healthy. Very fuel efficient.",
  },
  {
    id: "prod-6",
    title: "4-Plate Gas Stove + 19kg Cylinder",
    category: "Home",
    type: "Hardware",
    price: 165,
    currency: "$",
    condition: "New",
    seller: "Simba R.",
    initials: "SR",
    location: "Southerton, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-6/500/375",
    verified: false,
    postedAt: "7h ago",
    description: "Full kit with regulator, hose, 2-year warranty on stove.",
  },
  {
    id: "prod-7",
    title: "Queen Bed + Ortho Mattress + Headboard",
    category: "Home",
    type: "Furniture",
    price: 290,
    currency: "$",
    condition: "Used - excellent",
    seller: "Rudo C.",
    initials: "RC",
    location: "Greendale, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-7/500/375",
    verified: true,
    postedAt: "1d ago",
    description: "6 months old, no sagging. Buyer collects, can disassemble.",
  },
  {
    id: "prod-8",
    title: "L-Shaped Fabric Couch - Light Grey",
    category: "Home",
    type: "Furniture",
    price: 320,
    currency: "$",
    condition: "Used - good",
    seller: "Chipo Z.",
    initials: "CZ",
    location: "Avondale, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-8/500/375",
    verified: true,
    postedAt: "2d ago",
    description: "3.2m length, washable covers, very comfortable. No tears.",
  },
  {
    id: "prod-9",
    title: "3kVA Must Inverter + 2x 100Ah Lithium",
    category: "Home",
    type: "Hardware",
    price: 1150,
    currency: "$",
    condition: "New",
    seller: "PowerHub ZW",
    initials: "PZ",
    location: "Workington, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-9/500/375",
    verified: true,
    postedAt: "10h ago",
    description: "Powers fridge, TV, lights. Installation + warranty included.",
  },
  {
    id: "prod-10",
    title: "Shona Stone Sculpture - Family Unity 60cm",
    category: "Home",
    type: "Art",
    price: 120,
    currency: "$",
    condition: "New",
    seller: "Batsirai Crafts",
    initials: "BC",
    location: "Mbare, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-10/500/375",
    verified: false,
    postedAt: "3d ago",
    description: "Hand-carved serpentine, polished. One of a kind, heavy.",
  },
  {
    id: "prod-11",
    title: "Honda Fit GP5 2016 Hybrid - Low Mileage",
    category: "Vehicles",
    type: "Vehicles",
    price: 6950,
    currency: "$",
    condition: "Used",
    seller: "Blessing K.",
    initials: "BK",
    location: "Waterfalls, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-11/500/375",
    verified: true,
    postedAt: "1d ago",
    description: "Duty paid, reverse camera, new tyres. Ready to drive.",
  },
  {
    id: "prod-12",
    title: "Mazda Demio 2015 New Shape",
    category: "Vehicles",
    type: "Vehicles",
    price: 6200,
    currency: "$",
    condition: "Used",
    seller: "Tafadzwa B.",
    initials: "TB",
    location: "Chisipite, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-12/500/375",
    verified: false,
    postedAt: "2d ago",
    description: "Clean inside out, service history available. Price negotiable.",
  },
  {
    id: "prod-13",
    title: "Nike Air Jordan 4 Retro - Size 9",
    category: "Fashion",
    type: "Fashion",
    price: 95,
    currency: "$",
    condition: "New",
    seller: "Kudzai P.",
    initials: "KP",
    location: "Eastlea, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-13/500/375",
    verified: true,
    postedAt: "4h ago",
    description: "Original, box included. Limited stock, sizes 7-10 available.",
  },
  {
    id: "prod-14",
    title: "Ladies Ankara 2-Piece Set - M/L",
    category: "Fashion",
    type: "Fashion",
    price: 25,
    currency: "$",
    condition: "New",
    seller: "Nyasha T.",
    initials: "NT",
    location: "Highlands, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-14/500/375",
    verified: true,
    postedAt: "12h ago",
    description: "Tailored fit, vibrant print. Can custom make different sizes.",
  },
  {
    id: "prod-15",
    title: "925 Silver Necklace & Bracelet Set",
    category: "Fashion",
    type: "Jewelry",
    price: 70,
    currency: "$",
    condition: "New",
    seller: "Ruvarashe J.",
    initials: "RJ",
    location: "Mabelreign, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-15/500/375",
    verified: false,
    postedAt: "6h ago",
    description: "925 stamped, non-tarnish. Comes with gift box.",
  },
  {
    id: "prod-16",
    title: "Men's Chino Pants + Leather Belt Combo",
    category: "Fashion",
    type: "Fashion",
    price: 30,
    currency: "$",
    condition: "New",
    seller: "Panashe H.",
    initials: "PH",
    location: "CBD, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-16/500/375",
    verified: true,
    postedAt: "1d ago",
    description: "Khaki, black, navy available. Sizes 30-38. Genuine leather belt.",
  },
  {
    id: "prod-17",
    title: "Interior Painting & Skimming",
    category: "Services",
    type: "Services",
    price: 10,
    currency: "$",
    condition: "New",
    seller: "Pro Painters ZW",
    initials: "PP",
    location: "Citywide, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-17/500/375",
    verified: true,
    postedAt: "8h ago",
    description: "From $10 per sqm labour only. Free quote, neat work, same-day start.",
  },
  {
    id: "prod-18",
    title: "Wedding Photography & Videography",
    category: "Services",
    type: "Services",
    price: 250,
    currency: "$",
    condition: "New",
    seller: "Framed Moments",
    initials: "FM",
    location: "Citywide, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-18/500/375",
    verified: true,
    postedAt: "2d ago",
    description: "2 photographers, drone, 300 edited pics + 5min highlight video.",
  },
  {
    id: "prod-19",
    title: "5-Tonne Truck for Hire - Same Day",
    category: "Services",
    type: "Services",
    price: 40,
    currency: "$",
    condition: "New",
    seller: "Swift Movers",
    initials: "SM",
    location: "Citywide, Harare",
    image: "https://picsum.photos/seed/imba-market-v3-19/500/375",
    verified: true,
    postedAt: "3h ago",
    description: "House moves, deliveries, rubble. Price per load within Harare.",
  },
  {
    id: "prod-20",
    title: "O-Level Maths & Science Tutor - 5As Record",
    category: "Services",
    type: "Services",
    price: 8,
    currency: "$",
    condition: "New",
    seller: "Tadiwa M.",
    initials: "TM",
    location: "Online / Borrowdale",
    image: "https://picsum.photos/seed/imba-market-v3-20/500/375",
    verified: true,
    postedAt: "1d ago",
    description: "$8/hr online, $12 in person. ZIMSEC & Cambridge, exam packs included.",
  },
];