export const commerceCategories = ["All", "Electronics", "Fashion", "Home", "Vehicles", "Services"];

export const demoProducts = [
  { id: "c1", title: "iPhone 13 128GB", price: 450, currency: "USD", category: "Electronics", condition: "Used - good", location: "Harare", seller: "Tawanda", initials: "T", verified: true, description: "Clean device in good condition. Seller is available to answer questions and arrange a safe handover.", image: "https://images.unsplash.com/photo-1592286927505-2fd0c4cdd1b5?auto=format&fit=crop&w=900&q=80" },
  { id: "c2", title: "Minimal Oak Study Desk", price: 120, currency: "USD", category: "Home", condition: "Used - excellent", location: "Borrowdale", seller: "Rudo", initials: "R", verified: false, description: "Solid oak study desk with a simple finish. Message the seller to confirm measurements and collection details.", image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6b7?auto=format&fit=crop&w=900&q=80" },
  { id: "c3", title: "Nike Air Max", price: 55, currency: "USD", category: "Fashion", condition: "New", location: "Avondale", seller: "Brian", initials: "B", verified: true, description: "Genuine pair in new condition. Ask the seller about size, fit and pickup arrangements.", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80" },
  { id: "c4", title: "Bluetooth Speaker", price: 35, currency: "USD", category: "Electronics", condition: "Used - good", location: "Eastlea", seller: "Munashe", initials: "M", verified: false, description: "Portable Bluetooth speaker with a clean finish. Connect with the seller for battery and condition details.", image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80" },
  { id: "c5", title: "Toyota Corolla Parts", price: 80, currency: "USD", category: "Vehicles", condition: "Used", location: "Southerton", seller: "Kuda", initials: "K", verified: true, description: "Vehicle part listing. Confirm compatibility and inspect the item before paying.", image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80" },
  { id: "c6", title: "Graphic Design Package", price: 25, currency: "USD", category: "Services", condition: "Digital service", location: "Harare", seller: "Nyasha", initials: "N", verified: true, description: "A direct service listing. Message the seller to discuss your requirements, timing and price.", image: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80" },
];
