import Field from "./Field";
export default function BasicFields({ form, updateField, inputClass, inputStyle }) {
  return <>
    <Field label="LISTING TITLE *"><input className={inputClass} style={inputStyle} name="title" value={form.title} onChange={e=>updateField("title",e.target.value)} placeholder="Modern 2 Bedroom House" /></Field>
    <div className="grid grid-cols-2 gap-3"><Field label="SUBURB *"><input className={inputClass} style={inputStyle} name="suburb" value={form.suburb} onChange={e=>updateField("suburb",e.target.value)} placeholder="Westgate" /></Field><Field label="STREET / ADDRESS"><input className={inputClass} style={inputStyle} name="streetAddress" value={form.streetAddress} onChange={e=>updateField("streetAddress",e.target.value)} placeholder="Address" /></Field></div>
    <div className="grid grid-cols-2 gap-3"><Field label="PROPERTY TYPE"><select className={inputClass} style={inputStyle} name="type" value={form.type} onChange={e=>updateField("type",e.target.value)}>{["House","Flat","Cottage","Room","Garden Flat","Townhouse","Commercial","Land"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="AVAILABILITY"><select className={inputClass} style={inputStyle} name="availability" value={form.availability} onChange={e=>updateField("availability",e.target.value)}><option>Available now</option><option>Available next month</option><option>Available on request</option></select></Field></div>
    <div className="grid grid-cols-2 gap-3"><Field label="MONTHLY RENT ($) *"><input type="number" min="1" className={inputClass} style={inputStyle} name="rent" value={form.rent} onChange={e=>updateField("rent",e.target.value)} /></Field><Field label="DEPOSIT ($)"><input type="number" min="0" className={inputClass} style={inputStyle} name="deposit" value={form.deposit} onChange={e=>updateField("deposit",e.target.value)} /></Field></div>
    <div className="grid grid-cols-3 gap-2"><Field label="BEDROOMS"><input type="number" min="0" className={inputClass} style={inputStyle} name="rooms" value={form.rooms} onChange={e=>updateField("rooms",e.target.value)} /></Field><Field label="BATHROOMS"><input type="number" min="0" className={inputClass} style={inputStyle} name="bathrooms" value={form.bathrooms} onChange={e=>updateField("bathrooms",e.target.value)} /></Field><Field label="LEASE"><select className={inputClass} style={inputStyle} name="leaseTerm" value={form.leaseTerm} onChange={e=>updateField("leaseTerm",e.target.value)}><option>12 months</option><option>6 months</option><option>Month-to-month</option></select></Field></div>
    <div className="grid grid-cols-2 gap-3"><Field label="ELECTRICITY"><input className={inputClass} style={inputStyle} name="electricity" value={form.electricity} onChange={e=>updateField("electricity",e.target.value)} /></Field><Field label="WATER"><input className={inputClass} style={inputStyle} name="water" value={form.water} onChange={e=>updateField("water",e.target.value)} /></Field></div>
  </>;
}
