-- ImbaLink monetization intelligence / Marketplace-style analytics.
-- No billing is activated here. Metrics are operational and estimate demand,
-- eligibility and conversion opportunity from existing platform activity.

CREATE OR REPLACE FUNCTION public.get_monetization_analytics(p_days integer DEFAULT 30)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_days integer := greatest(7, least(coalesce(p_days, 30), 365));
  v_from timestamptz := now() - make_interval(days => v_days);
  v_prev_from timestamptz := v_from - make_interval(days => v_days);
  v_enabled boolean := coalesce((SELECT enabled FROM public.monetization_settings WHERE id=1), false);
  v_users bigint := 0; v_verified bigint := 0; v_pro bigint := 0; v_eligible bigint := 0;
  v_views bigint := 0; v_requests bigint := 0; v_locked bigint := 0;
  v_pro_listings bigint := 0; v_total_listings bigint := 0;
  v_prev_pro bigint := 0; v_prev_verified bigint := 0;
  v_series jsonb; v_account_mix jsonb;
BEGIN
  IF NOT public.is_staff_caller() THEN RAISE EXCEPTION 'STAFF_ROLE_REQUIRED'; END IF;

  SELECT count(*) INTO v_users FROM public.users;

  SELECT count(*) INTO v_verified
  FROM public.users u
  WHERE
    (u.account_type='student' AND EXISTS (SELECT 1 FROM public.student_profiles sp WHERE sp.user_id=u.id AND sp.verification_status='verified'))
    OR (u.account_type='landlord' AND EXISTS (SELECT 1 FROM public.landlord_verifications lv WHERE lv.user_id=u.id AND lv.verification_status='verified'))
    OR (u.account_type IN ('agent','company') AND EXISTS (SELECT 1 FROM public.registrations r WHERE r.user_id=u.id AND r.kind=u.account_type AND r.verification_status='verified'))
    OR (u.account_type='contractor' AND EXISTS (SELECT 1 FROM public.contractors c WHERE c.user_id=u.id AND c.verification='verified'));

  SELECT count(*) INTO v_pro
  FROM public.pro_registrations pr
  WHERE coalesce(pr.status,'active')='active'
    AND (pr.starts_at IS NULL OR pr.starts_at <= now())
    AND (pr.expires_at IS NULL OR pr.expires_at > now());

  v_eligible := v_verified;

  SELECT count(*) INTO v_total_listings FROM public.properties WHERE owner_user_id IS NOT NULL;
  SELECT count(*) INTO v_pro_listings
  FROM public.properties p
  WHERE p.owner_user_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.pro_registrations pr
    WHERE pr.user_id=p.owner_user_id AND coalesce(pr.status,'active')='active'
      AND (pr.starts_at IS NULL OR pr.starts_at <= now())
      AND (pr.expires_at IS NULL OR pr.expires_at > now())
  );

  SELECT coalesce(sum(p.view_count),0) INTO v_views FROM public.properties p WHERE p.owner_user_id IS NOT NULL;
  SELECT count(*) INTO v_requests FROM public.viewing_requests WHERE created_at >= v_from;

  -- Requests generated by users who would currently be blocked by the Pro gate
  -- are the best available proxy for monetization pressure until billing exists.
  SELECT count(*) INTO v_locked
  FROM public.viewing_requests vr
  WHERE vr.created_at >= v_from
    AND NOT EXISTS (
      SELECT 1 FROM public.pro_registrations pr
      WHERE pr.user_id=vr.user_id AND coalesce(pr.status,'active')='active'
        AND (pr.starts_at IS NULL OR pr.starts_at <= vr.created_at)
        AND (pr.expires_at IS NULL OR pr.expires_at > vr.created_at)
    );

  SELECT count(*) INTO v_prev_pro FROM public.pro_registrations pr
  WHERE pr.created_at >= v_prev_from AND pr.created_at < v_from;
  SELECT count(*) INTO v_prev_verified FROM public.users u
  WHERE u.created_at >= v_prev_from AND u.created_at < v_from
    AND (
      (u.account_type='student' AND EXISTS (SELECT 1 FROM public.student_profiles sp WHERE sp.user_id=u.id AND sp.verification_status='verified'))
      OR (u.account_type='landlord' AND EXISTS (SELECT 1 FROM public.landlord_verifications lv WHERE lv.user_id=u.id AND lv.verification_status='verified'))
      OR (u.account_type IN ('agent','company') AND EXISTS (SELECT 1 FROM public.registrations r WHERE r.user_id=u.id AND r.kind=u.account_type AND r.verification_status='verified'))
      OR (u.account_type='contractor' AND EXISTS (SELECT 1 FROM public.contractors c WHERE c.user_id=u.id AND c.verification='verified'))
    );

  WITH days AS (
    SELECT generate_series(current_date - (v_days-1), current_date, interval '1 day')::date AS d
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'date', to_char(d,'Mon DD'),
    'pro', (SELECT count(*) FROM pro_registrations pr WHERE pr.created_at::date=d),
    'verified', (SELECT count(*) FROM users u WHERE u.created_at::date=d AND (
      (u.account_type='student' AND EXISTS (SELECT 1 FROM student_profiles sp WHERE sp.user_id=u.id AND sp.verification_status='verified')) OR
      (u.account_type='landlord' AND EXISTS (SELECT 1 FROM landlord_verifications lv WHERE lv.user_id=u.id AND lv.verification_status='verified')) OR
      (u.account_type IN ('agent','company') AND EXISTS (SELECT 1 FROM registrations r WHERE r.user_id=u.id AND r.kind=u.account_type AND r.verification_status='verified')) OR
      (u.account_type='contractor' AND EXISTS (SELECT 1 FROM contractors c WHERE c.user_id=u.id AND c.verification='verified'))
    )),
    'requests', (SELECT count(*) FROM viewing_requests vr WHERE vr.created_at::date=d),
    'views', (SELECT coalesce(sum(p.view_count),0) FROM properties p WHERE p.created_at::date=d)
  ) ORDER BY d),'[]'::jsonb) INTO v_series FROM days;

  SELECT coalesce(jsonb_agg(jsonb_build_object('label',coalesce(account_type::text,'unknown'),'value',n) ORDER BY n DESC),'[]'::jsonb)
  INTO v_account_mix
  FROM (SELECT account_type, count(*) n FROM users GROUP BY account_type) x;

  RETURN jsonb_build_object(
    'enabled', v_enabled,
    'period_days', v_days,
    'kpis', jsonb_build_object(
      'total_users', v_users,
      'verified_users', v_verified,
      'active_pro', v_pro,
      'eligible_users', v_eligible,
      'pro_penetration', CASE WHEN v_users=0 THEN 0 ELSE round((v_pro::numeric/v_users)*100,1) END,
      'verification_rate', CASE WHEN v_users=0 THEN 0 ELSE round((v_verified::numeric/v_users)*100,1) END,
      'pro_listings', v_pro_listings,
      'total_landlord_listings', v_total_listings,
      'pro_listing_share', CASE WHEN v_total_listings=0 THEN 0 ELSE round((v_pro_listings::numeric/v_total_listings)*100,1) END,
      'period_views', v_views,
      'period_requests', v_requests,
      'locked_opportunity', v_locked,
      'pro_growth', v_prev_pro,
      'verified_growth', v_prev_verified,
      'billing_ready', false
    ),
    'series', v_series,
    'account_mix', v_account_mix,
    'insights', jsonb_build_array(
      jsonb_build_object('label','Verified audience','value',v_verified,'description','Accounts currently eligible for Pro once they also have an active membership.'),
      jsonb_build_object('label','Pro penetration','value',CASE WHEN v_users=0 THEN 0 ELSE round((v_pro::numeric/v_users)*100,1) END,'description','Active Pro accounts as a share of all users.'),
      jsonb_build_object('label','Monetization pressure','value',v_locked,'description','Viewing requests from users without an active Pro membership in the selected period.'),
      jsonb_build_object('label','Pro inventory share','value',CASE WHEN v_total_listings=0 THEN 0 ELSE round((v_pro_listings::numeric/v_total_listings)*100,1) END,'description','Listings owned by accounts with active Pro access.')
    )
  );
END;
$$;
REVOKE ALL ON FUNCTION public.get_monetization_analytics(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_monetization_analytics(integer) TO authenticated;



-- Defense-in-depth: every viewing request is checked at the database boundary.
-- This covers stale clients and direct API calls; the UI/realtime layer is only
-- the presentation layer of the same policy.
CREATE OR REPLACE FUNCTION public.require_pro_for_viewing_request()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_access jsonb;
BEGIN
  IF COALESCE((SELECT enabled FROM public.monetization_settings WHERE id=1), false) = false THEN
    RETURN NEW;
  END IF;
  IF COALESCE(auth.jwt()->'app_metadata'->>'role','') = 'admin' THEN RETURN NEW; END IF;
  v_access := public.get_my_pro_access();
  IF COALESCE((v_access->>'can_access')::boolean, false) = false THEN
    RAISE EXCEPTION 'PRO_ACCESS_REQUIRED';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS require_pro_for_viewing_request ON public.viewing_requests;
CREATE TRIGGER require_pro_for_viewing_request
BEFORE INSERT ON public.viewing_requests
FOR EACH ROW EXECUTE FUNCTION public.require_pro_for_viewing_request();

NOTIFY pgrst, 'reload schema';
