import React,{useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowUpRight,BarChart3,CheckCircle2,CircleDollarSign,Clock3,Info,RefreshCw,ShieldCheck,TrendingUp,Users,WalletCards} from "lucide-react";
import {getMonetizationConfig,setMonetizationEnabled,getMonetizationAnalytics} from "../../services/admin/adminMonetization";
import {adminFormat} from "../../services/admin/adminAnalytics";
import useAdminRealtime from "../../hooks/useAdminRealtime";

function Metric({label,value,sub,icon:Icon,tone="green"}){return <div className={`admin-monetary-metric tone-${tone}`}><div className="admin-monetary-metric-top"><span>{label}</span><Icon size={16}/></div><strong>{value}</strong><small>{sub}</small></div>}
function ConfirmModal({open,next,onCancel,onConfirm,busy}){if(!open)return null;const enabling=next;return <div className="admin-modal-backdrop"><div className="admin-modal admin-confirm-modal" role="dialog" aria-modal="true"><div className="admin-modal-head"><div><span className="admin-kicker"><AlertTriangle size={14}/> Major platform change</span><h2>{enabling?"Enable monetization?":"Disable monetization?"}</h2><p>This changes a platform-wide business rule and should be reviewed before it is saved.</p></div></div><div className="admin-alert"><AlertTriangle size={17}/><span>{enabling?"New listing and viewing-request Pro gates will become enforceable for eligible users.":"Monetization gates will stop enforcing, allowing the affected premium actions to proceed without Pro access."}</span></div><div className="admin-confirm-checklist"><b>Before saving</b><span>• Confirm the intended launch/maintenance window.</span><span>• Confirm support and customer messaging are ready.</span><span>• Confirm verification and Pro eligibility data is healthy.</span></div><div className="admin-modal-foot"><button className="admin-button secondary" onClick={onCancel}>Cancel</button><button className="admin-button" disabled={busy} onClick={onConfirm}>{busy?<><RefreshCw size={14} className="admin-spin"/> Saving…</>:<><ShieldCheck size={14}/> Confirm & save</>}</button></div></div></div>}

export default function AdminMonetizationPage(){
 const [config,setConfig]=useState(null),[analytics,setAnalytics]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[confirm,setConfirm]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const [c,a]=await Promise.all([getMonetizationConfig(),getMonetizationAnalytics(30)]);setConfig(c);setAnalytics(a)}catch(e){setError(e?.message||"Unable to load monetization intelligence.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);useAdminRealtime(()=>load());
 const save=async()=>{if(!config)return;setBusy(true);try{const next=!config.enabled;const c=await setMonetizationEnabled(next);setConfig(c||{...config,enabled:next});setConfirm(false)}catch(e){setError(e?.message||"Unable to save monetization settings.")}finally{setBusy(false)}};
 const k=analytics?.kpis||{};const series=Array.isArray(analytics?.series)?analytics.series:[];const max=Math.max(1,...series.map(x=>Number(x.requests||0)+Number(x.pro||0)));
 const insights=analytics?.insights||[];
 const readiness=useMemo(()=>[{label:"Verified audience",value:k.verified_users||0,ok:Number(k.verified_users||0)>0,desc:"Verified accounts that can become eligible for Pro."},{label:"Active Pro",value:k.active_pro||0,ok:Number(k.active_pro||0)>0,desc:"Current active Pro memberships."},{label:"Pro penetration",value:adminFormat.percent(k.pro_penetration),ok:true,desc:"Active Pro accounts as a share of all users."},{label:"Billing readiness",value:k.billing_ready?"Ready":"Not connected",ok:Boolean(k.billing_ready),desc:"A payment processor is not connected in this release."}],[k]);
 return <div className="admin-page"><div className="admin-page-title"><div><div className="admin-breadcrumb">Administration <span>/</span> Monetization</div><h1>Monetization</h1><p>Revenue strategy, Pro adoption, eligibility health and launch readiness — built as the commercial control room for ImbaLink.</p></div><div className="admin-page-actions"><span className={`admin-live-status ${config?.enabled?"on":"off"}`}><i/>{config?.enabled?"Monetization live":"Monetization off"}</span><button className="admin-button secondary" onClick={load}><RefreshCw size={14}/> Refresh</button></div></div>
 {error&&<div className="admin-alert"><span>{error}</span><button onClick={load}>Retry</button></div>}
 {loading&&!analytics?<div className="admin-loading"><div/><div/><div/><div/></div>:<>
 <section className="admin-monetization-hero"><div><span className="admin-kicker"><CircleDollarSign size={14}/> Marketplace revenue strategy</span><h2>{config?.enabled?"Monetization is enforcing Pro access":"Monetization is in controlled-off mode"}</h2><p>{config?.enabled?"The platform is currently enforcing the Pro eligibility gates defined in Supabase. Monitor conversion, verification and support load before expanding paid access.":"You can safely prepare pricing, entitlement rules and customer messaging before turning on enforcement. No payment processor is connected yet."}</p></div><div className="admin-monetization-switch"><div><small>Platform enforcement</small><b>{config?.enabled?"ON":"OFF"}</b></div><button className={`admin-switch ${config?.enabled?"is-on":""}`} onClick={()=>setConfirm(true)} disabled={!config||busy} aria-label="Change monetization status"><span/></button></div></section>
 <div className="admin-kpi-grid"><Metric label="Active Pro" value={adminFormat.number(k.active_pro)} sub={`${adminFormat.percent(k.pro_penetration)} of all users`} icon={WalletCards}/><Metric label="Verified users" value={adminFormat.number(k.verified_users)} sub={`${adminFormat.percent(k.verification_rate)} of all users`} icon={ShieldCheck} tone="teal"/><Metric label="Locked opportunity" value={adminFormat.number(k.locked_opportunity)} sub="Requests from non-Pro users" icon={TrendingUp} tone="purple"/><Metric label="Pro listings" value={adminFormat.number(k.pro_listings)} sub={`${adminFormat.percent(k.pro_listing_share)} of listings`} icon={BarChart3} tone="blue"/></div>
 <div className="admin-grid admin-grid-main"><section className="admin-panel"><div className="admin-panel-head"><div><h2>Commercial health</h2><p>Signals to watch before changing pricing or enforcement.</p></div></div><div className="admin-readiness-grid">{readiness.map(x=><div className="admin-readiness-card" key={x.label}><span className={x.ok?"ok":"warn"}>{x.ok?<CheckCircle2 size={15}/>:<Clock3 size={15}/>}</span><div><small>{x.label}</small><b>{x.value}</b><p>{x.desc}</p></div></div>)}</div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>30-day opportunity</h2><p>Demand that is not currently covered by Pro.</p></div><ArrowUpRight size={17}/></div><div className="admin-opportunity-number">{adminFormat.number(k.locked_opportunity)}</div><p className="admin-cell-muted">Viewing requests from accounts without an active Pro membership. This is a demand signal, not recognized revenue.</p><div className="admin-opportunity-note"><Info size={14}/> Do not treat this as revenue until pricing, payment collection, refunds and reconciliation are implemented.</div></section></div>
 <div className="admin-grid admin-grid-main"><section className="admin-panel"><div className="admin-panel-head"><div><h2>Demand & Pro trend</h2><p>Daily requests and Pro registrations over the selected 30-day window.</p></div></div><div className="admin-monetization-bars">{series.map((x,i)=><div className="admin-monetization-day" key={x.date||i} title={`${x.date||""}: ${x.requests||0} requests, ${x.pro||0} Pro`}><span style={{height:`${Math.max(3,Number(x.requests||0)/max*100)}%`}}/><i style={{height:`${Math.max(3,Number(x.pro||0)/max*100)}%`}}/></div>)}</div><div className="admin-chart-legend"><span><i/> Requests</span><span><i/> Pro registrations</span></div></section><section className="admin-panel"><div className="admin-panel-head"><div><h2>Monetization insights</h2><p>What the current data suggests.</p></div></div><div className="admin-insight-list">{insights.length?insights.map((x,i)=><div key={i}><b>{x.label}</b><strong>{typeof x.value==="number"?adminFormat.number(x.value):x.value}</strong><p>{x.description}</p></div>):<div className="admin-empty-inline">No insights available.</div>}</div></section></div>
 <section className="admin-panel"><div className="admin-panel-head"><div><h2>Airbnb-style monetization roadmap</h2><p>A practical sequence for turning this control room into a real revenue system without compromising trust.</p></div></div><div className="admin-roadmap"><div><span>01</span><b>Define the value proposition</b><p>Decide exactly which landlord, agent, student or contractor outcomes justify Pro and document the benefit in plain language.</p></div><div><span>02</span><b>Introduce pricing experiments</b><p>Test monthly plans, annual discounts and introductory offers against conversion, retention and support volume.</p></div><div><span>03</span><b>Connect payments</b><p>Add a payment provider, transaction ledger, webhook reconciliation, refunds, failed-payment handling and entitlement expiry.</p></div><div><span>04</span><b>Protect trust & conversion</b><p>Keep verification separate from payment, show clear renewal terms, preserve existing listings and provide an auditable support trail.</p></div></div></section>
 <div className="admin-monetization-footer-note"><Info size={15}/><span><b>Important:</b> this release provides monetization controls and analytics only. It does not claim revenue that has not been collected, and it does not connect a payment processor.</span></div>
 </>}
 <ConfirmModal open={confirm} next={!config?.enabled} onCancel={()=>setConfirm(false)} onConfirm={save} busy={busy}/>
 </div>;
}
