import { useEffect, useState } from "react";
import { X, CheckCircle2, ChevronRight } from "lucide-react";
import { T } from "../../styles/tokens";
import { useBodyScrollLock } from "../../hooks/useBodyScrollLock";

const SPECIALIZATIONS=["Residential Sales","Residential Letting","Commercial Sales","Commercial Letting","Industrial Property","Land & Stands","Property Management","Farms & Agricultural","New Developments","Valuations"];
const YEARS=["Less than 1 year","1–2 years","3–5 years","6–10 years","10+ years"];
const AREAS=["Harare CBD","Avondale","Borrowdale","Chisipite","Eastlea","Greendale","Hatfield","Highlands","Mbare","Mount Pleasant","Newlands","Westgate","Westlea","Other Harare areas"];
const AFFILIATIONS=["Independent agent","Attached to an agency","Company representative"];
export default function AgentRegistration({onClose,onSubmit,profile}){
 const [step,setStep]=useState(1); const [error,setError]=useState("");
 const [form,setForm]=useState({fullName:`${profile?.firstName || ""} ${profile?.surname || ""}`.trim(),agencyName:"",affiliation:"Independent agent",phone:profile?.phone || "",email:"",officeAddress:"",username:"",password:"",confirmPassword:"",specializations:[],areas:[],yearsExperience:"",eaczNumber:"",licenseNumber:"",taxNumber:"",idType:"National ID",idNumber:"",description:"",offersValuations:false,acceptsListingLeads:true,agreesTerms:false});
 const update=(k,v)=>setForm(f=>({...f,[k]:v})); const toggle=(k,v)=>setForm(f=>({...f,[k]:f[k].includes(v)?f[k].filter(x=>x!==v):[...f[k],v]}));
 const next=()=>{setError("");if(step===1&&(!form.fullName.trim()||!form.phone.trim()||!form.email.trim()))return setError("Complete your personal and contact details.");if(step===1&&!form.username.trim())return setError("Choose a username for your agent login.");if(step===1&&(!form.password||form.password.length<6))return setError("Password must be at least 6 characters.");if(step===1&&form.password!==form.confirmPassword)return setError("Passwords do not match.");if(step===2&&(!form.specializations.length||!form.yearsExperience||!form.areas.length))return setError("Select your specializations, experience and service areas.");setStep(s=>Math.min(4,s+1));};
 const submit=async e=>{e.preventDefault();if(!form.agreesTerms)return setError("You must confirm the registration declaration.");const {confirmPassword,...payload}=form;try{await onSubmit({...payload,fullName:form.fullName.trim(),agencyName:form.agencyName.trim(),description:form.description.trim(),username:form.username.trim()});}catch(err){setError(err?.message||"Could not complete agent registration.");}};
 const input="w-full rounded-xl px-3 py-2.5 f-body outline-none",style={background:T.paperDim,color:T.ink,border:`1px solid ${T.line}`,fontSize:12};
 const Field=({label,children})=><label className="block"><span className="f-body font-semibold block mb-1.5" style={{color:T.ink60,fontSize:10}}>{label}</span>{children}</label>;
 return <div className="fixed inset-0 z-[1000] sm:z-50 flex items-end sm:items-center justify-center form-modal-backdrop" style={{background:"rgba(20,32,26,.68)"}}><form onSubmit={submit} className="w-full sm:max-w-xl rounded-t-[28px] sm:rounded-[28px] p-5 form-modal-panel" style={{background:T.paper,maxHeight:"92%",overflowY:"auto"}}>
  <div className="flex justify-between items-start mb-4"><div><div className="f-display font-bold" style={{color:T.ink,fontSize:18}}>Register as an agent</div><div className="f-body mt-1" style={{color:T.ink60,fontSize:10.5}}>Your profile is reviewed before the verified badge is issued.</div></div><button type="button" onClick={onClose} className="w-9 h-9 rounded-full flex items-center justify-center" style={{background:T.paperDim}}><X size={17}/></button></div>
  <div className="flex gap-1.5 mb-5">{[1,2,3,4].map(n=><div key={n} className="h-1.5 rounded-full flex-1" style={{background:n<=step?T.brick:T.line}}/>)}</div>
  {step===1&&<div className="space-y-3"><Field label="FULL NAME *"><input className={input} style={style} value={form.fullName} onChange={e=>update("fullName",e.target.value)} placeholder="Your legal/full name"/></Field><Field label="AFFILIATION"><select className={input} style={style} value={form.affiliation} onChange={e=>update("affiliation",e.target.value)}>{AFFILIATIONS.map(x=><option key={x}>{x}</option>)}</select></Field>{form.affiliation!=="Independent agent"&&<Field label="AGENCY / COMPANY NAME"><input className={input} style={style} value={form.agencyName} onChange={e=>update("agencyName",e.target.value)} placeholder="e.g. Zimre Properties"/></Field>}<div className="grid grid-cols-2 gap-3"><Field label="PHONE *"><input className={input} style={style} value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+263..."/></Field><Field label="EMAIL *"><input type="email" className={input} style={style} value={form.email} onChange={e=>update("email",e.target.value)} placeholder="you@example.com"/></Field></div><Field label="OFFICE ADDRESS"><input className={input} style={style} value={form.officeAddress} onChange={e=>update("officeAddress",e.target.value)} placeholder="Office / operating address"/></Field><div className="f-mono" style={{color:T.ink60,fontSize:10,letterSpacing:".08em"}}>ACCOUNT LOGIN</div><Field label="USERNAME *"><input className={input} style={style} value={form.username} onChange={e=>update("username",e.target.value)} placeholder="Choose a username" autoComplete="username"/></Field><div className="grid grid-cols-2 gap-3"><Field label="PASSWORD *"><input type="password" className={input} style={style} value={form.password} onChange={e=>update("password",e.target.value)} placeholder="At least 6 characters" autoComplete="new-password"/></Field><Field label="CONFIRM PASSWORD *"><input type="password" className={input} style={style} value={form.confirmPassword} onChange={e=>update("confirmPassword",e.target.value)} placeholder="Re-enter password" autoComplete="new-password"/></Field></div></div>}
  {step===2&&<div className="space-y-3"><Field label="SPECIALIZATIONS *"><div className="grid grid-cols-2 gap-2">{SPECIALIZATIONS.map(x=><label key={x} className="flex gap-2 items-center p-2.5 rounded-xl" style={{background:T.paperDim,fontSize:10.5,color:T.ink}}><input type="checkbox" checked={form.specializations.includes(x)} onChange={()=>toggle("specializations",x)}/>{x}</label>)}</div></Field><Field label="EXPERIENCE *"><select className={input} style={style} value={form.yearsExperience} onChange={e=>update("yearsExperience",e.target.value)}><option value="">Select experience</option>{YEARS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="SERVICE AREAS *"><div className="flex flex-wrap gap-1.5">{AREAS.map(x=><button type="button" key={x} onClick={()=>toggle("areas",x)} className="px-2.5 py-1.5 rounded-full f-body" style={{background:form.areas.includes(x)?T.jacaranda:T.paperDim,color:form.areas.includes(x)?T.paper:T.ink,fontSize:9.5}}>{x}</button>)}</div></Field></div>}
  {step===3&&<div className="space-y-3"><div className="rounded-xl p-3" style={{background:T.paperDim}}><div className="f-body font-semibold" style={{color:T.ink,fontSize:11}}>Verification information</div><div className="f-body mt-1" style={{color:T.ink60,fontSize:10}}>Supply identifiers you have. Missing numbers can be left blank and will be reviewed manually.</div></div><div className="grid grid-cols-2 gap-3"><Field label="ID TYPE"><select className={input} style={style} value={form.idType} onChange={e=>update("idType",e.target.value)}><option>National ID</option><option>Passport</option><option>Driver's Licence</option></select></Field><Field label="ID NUMBER"><input className={input} style={style} value={form.idNumber} onChange={e=>update("idNumber",e.target.value)}/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="EACZ REGISTRATION NO."><input className={input} style={style} value={form.eaczNumber} onChange={e=>update("eaczNumber",e.target.value)} placeholder="Estate Agents Council no."/></Field><Field label="LICENCE NO."><input className={input} style={style} value={form.licenseNumber} onChange={e=>update("licenseNumber",e.target.value)}/></Field></div><Field label="TAX / ZIMRA NUMBER"><input className={input} style={style} value={form.taxNumber} onChange={e=>update("taxNumber",e.target.value)}/></Field><Field label="PROFILE DESCRIPTION"><textarea rows="4" className={input} style={style} value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Tell clients what makes your service reliable."/></Field></div>}
  {step===4&&<div className="space-y-3"><div className="rounded-2xl p-4" style={{background:T.paperDim}}><div className="flex items-center gap-2"><CheckCircle2 size={17} style={{color:T.msasa}}/><span className="f-display font-semibold" style={{color:T.ink,fontSize:13}}>Final registration checks</span></div><div className="f-body mt-3 space-y-2" style={{color:T.ink60,fontSize:10.5}}><div>✓ Accurate contact and affiliation information</div><div>✓ Correct specializations selected</div><div>✓ Service areas and experience supplied</div><div>✓ Verification identifiers supplied where available</div><div>✓ Profile is verified and ready to appear in the app</div></div></div><label className="flex gap-2.5 p-3 rounded-xl" style={{background:T.paperDim}}><input type="checkbox" checked={form.offersValuations} onChange={e=>update("offersValuations",e.target.checked)}/><span className="f-body" style={{fontSize:11,color:T.ink}}>I offer property valuation services.</span></label><label className="flex gap-2.5 p-3 rounded-xl" style={{background:T.paperDim}}><input type="checkbox" checked={form.acceptsListingLeads} onChange={e=>update("acceptsListingLeads",e.target.checked)}/><span className="f-body" style={{fontSize:11,color:T.ink}}>I am available to receive listing and client leads.</span></label><label className="flex gap-2.5 p-3 rounded-xl" style={{background:T.paperDim}}><input type="checkbox" checked={form.agreesTerms} onChange={e=>update("agreesTerms",e.target.checked)}/><span className="f-body" style={{fontSize:11,color:T.ink}}>I confirm that the information supplied is accurate and I agree to ImbaLink's agent rules.</span></label></div>}
  {error&&<div className="mt-3 rounded-xl p-3 f-body" style={{background:"rgba(184,61,49,.1)",color:T.brick,fontSize:10.5}}>{error}</div>}
  <div className="flex gap-2 mt-5">{step>1&&<button type="button" onClick={()=>setStep(s=>s-1)} className="px-5 py-3 rounded-full f-body font-semibold" style={{background:T.paperDim,color:T.ink,fontSize:11}}>Back</button>}{step<4?<button type="button" onClick={next} className="flex-1 py-3 rounded-full f-display font-semibold flex justify-center items-center gap-2" style={{background:T.brick,color:T.paper,fontSize:12}}>Continue <ChevronRight size={15}/></button>:<button type="submit" className="flex-1 py-3 rounded-full f-display font-semibold" style={{background:T.brick,color:T.paper,fontSize:12}}>Submit agent registration</button>}</div>
 </form></div>;
}
