import { useEffect, useState } from "react";
import { X, CheckCircle2, ChevronRight } from "lucide-react";
import { T } from "../../styles/tokens";
import { useBodyScrollLock } from "../../hooks/useBodyScrollLock";

const COMPANY_TYPES=["Real Estate Agency","Property Management Firm","Property Developer","Construction Company","Facilities Management","Investment / Holding Company","Other"];
const SERVICES=["Property Sales","Property Letting","Property Management","New Developments","Valuations","Facilities Management","Consultation","Construction & Renovation"];
const YEARS=["Less than 1 year","1–2 years","3–5 years","6–10 years","10+ years"];
const AREAS=["Harare CBD","Avondale","Borrowdale","Chisipite","Eastlea","Greendale","Hatfield","Highlands","Mbare","Mount Pleasant","Newlands","Westgate","Westlea","Other Harare areas"];
const STAFF_SIZES=["1–5","6–15","16–50","51–100","100+"];
export default function CompanyRegistration({onClose,onSubmit,profile}){
 const [step,setStep]=useState(1); const [error,setError]=useState("");
 const [form,setForm]=useState({companyName:"",tradingName:"",repName:`${profile?.firstName || ""} ${profile?.surname || ""}`.trim(),repRole:"",phone:profile?.phone || "",email:"",registeredAddress:"",username:"",password:"",confirmPassword:"",companyType:"",services:[],areas:[],yearsOperating:"",staffSize:"",registrationNumber:"",eaczNumber:"",taxNumber:"",directorIdType:"National ID",directorIdNumber:"",description:"",offersValuations:false,acceptsListingLeads:true,agreesTerms:false});
 const update=(k,v)=>setForm(f=>({...f,[k]:v})); const toggle=(k,v)=>setForm(f=>({...f,[k]:f[k].includes(v)?f[k].filter(x=>x!==v):[...f[k],v]}));
 const next=()=>{setError("");if(step===1&&(!form.companyName.trim()||!form.repName.trim()||!form.phone.trim()||!form.email.trim()))return setError("Complete your company and representative contact details.");if(step===1&&!form.username.trim())return setError("Choose a username for your company login.");if(step===1&&(!form.password||form.password.length<6))return setError("Password must be at least 6 characters.");if(step===1&&form.password!==form.confirmPassword)return setError("Passwords do not match.");if(step===2&&(!form.companyType||!form.services.length||!form.areas.length))return setError("Select your company type, services and service areas.");setStep(s=>Math.min(4,s+1));};
 const submit=async e=>{e.preventDefault();if(!form.agreesTerms)return setError("You must confirm the registration declaration.");const {confirmPassword,...payload}=form;try{await onSubmit({...payload,companyName:form.companyName.trim(),tradingName:form.tradingName.trim(),repName:form.repName.trim(),description:form.description.trim(),username:form.username.trim()});}catch(err){setError(err?.message||"Could not complete company registration.");}};
 const input="w-full rounded-xl px-3 py-2.5 f-body outline-none",style={background:T.paperDim,color:T.ink,border:`1px solid ${T.line}`,fontSize:12};
 const Field=({label,children})=><label className="block"><span className="f-body font-semibold block mb-1.5" style={{color:T.ink60,fontSize:10}}>{label}</span>{children}</label>;
 return <div className="fixed inset-0 z-[1000] sm:z-50 flex items-end sm:items-center justify-center form-modal-backdrop" style={{background:"rgba(20,32,26,.68)"}}><form onSubmit={submit} className="w-full sm:max-w-xl rounded-t-[28px] sm:rounded-[28px] p-5 form-modal-panel" style={{background:T.paper,maxHeight:"92%",overflowY:"auto"}}>
  <div className="flex justify-between items-start mb-4"><div><div className="f-display font-bold" style={{color:T.ink,fontSize:18}}>Register a company</div><div className="f-body mt-1" style={{color:T.ink60,fontSize:10.5}}>Your profile is reviewed before the verified badge is issued.</div></div><button type="button" onClick={onClose} className="w-9 h-9 rounded-full flex items-center justify-center" style={{background:T.paperDim}}><X size={17}/></button></div>
  <div className="flex gap-1.5 mb-5">{[1,2,3,4].map(n=><div key={n} className="h-1.5 rounded-full flex-1" style={{background:n<=step?T.brick:T.line}}/>)}</div>
  {step===1&&<div className="space-y-3"><Field label="COMPANY NAME *"><input className={input} style={style} value={form.companyName} onChange={e=>update("companyName",e.target.value)} placeholder="Registered company name"/></Field><Field label="TRADING NAME"><input className={input} style={style} value={form.tradingName} onChange={e=>update("tradingName",e.target.value)} placeholder="If different from registered name"/></Field><div className="grid grid-cols-2 gap-3"><Field label="REPRESENTATIVE NAME *"><input className={input} style={style} value={form.repName} onChange={e=>update("repName",e.target.value)} placeholder="Person registering"/></Field><Field label="REPRESENTATIVE ROLE"><input className={input} style={style} value={form.repRole} onChange={e=>update("repRole",e.target.value)} placeholder="e.g. Director, Manager"/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="PHONE *"><input className={input} style={style} value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+263..."/></Field><Field label="EMAIL *"><input type="email" className={input} style={style} value={form.email} onChange={e=>update("email",e.target.value)} placeholder="company@example.com"/></Field></div><Field label="REGISTERED ADDRESS"><input className={input} style={style} value={form.registeredAddress} onChange={e=>update("registeredAddress",e.target.value)} placeholder="Registered / operating address"/></Field><div className="f-mono" style={{color:T.ink60,fontSize:10,letterSpacing:".08em"}}>ACCOUNT LOGIN</div><Field label="USERNAME *"><input className={input} style={style} value={form.username} onChange={e=>update("username",e.target.value)} placeholder="Choose a username" autoComplete="username"/></Field><div className="grid grid-cols-2 gap-3"><Field label="PASSWORD *"><input type="password" className={input} style={style} value={form.password} onChange={e=>update("password",e.target.value)} placeholder="At least 6 characters" autoComplete="new-password"/></Field><Field label="CONFIRM PASSWORD *"><input type="password" className={input} style={style} value={form.confirmPassword} onChange={e=>update("confirmPassword",e.target.value)} placeholder="Re-enter password" autoComplete="new-password"/></Field></div></div>}
  {step===2&&<div className="space-y-3"><Field label="COMPANY TYPE *"><select className={input} style={style} value={form.companyType} onChange={e=>update("companyType",e.target.value)}><option value="">Select company type</option>{COMPANY_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="SERVICES OFFERED *"><div className="grid grid-cols-2 gap-2">{SERVICES.map(x=><label key={x} className="flex gap-2 items-center p-2.5 rounded-xl" style={{background:T.paperDim,fontSize:10.5,color:T.ink}}><input type="checkbox" checked={form.services.includes(x)} onChange={()=>toggle("services",x)}/>{x}</label>)}</div></Field><div className="grid grid-cols-2 gap-3"><Field label="YEARS OPERATING"><select className={input} style={style} value={form.yearsOperating} onChange={e=>update("yearsOperating",e.target.value)}><option value="">Select</option>{YEARS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="STAFF SIZE"><select className={input} style={style} value={form.staffSize} onChange={e=>update("staffSize",e.target.value)}><option value="">Select</option>{STAFF_SIZES.map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="SERVICE AREAS *"><div className="flex flex-wrap gap-1.5">{AREAS.map(x=><button type="button" key={x} onClick={()=>toggle("areas",x)} className="px-2.5 py-1.5 rounded-full f-body" style={{background:form.areas.includes(x)?T.jacaranda:T.paperDim,color:form.areas.includes(x)?T.paper:T.ink,fontSize:9.5}}>{x}</button>)}</div></Field></div>}
  {step===3&&<div className="space-y-3"><div className="rounded-xl p-3" style={{background:T.paperDim}}><div className="f-body font-semibold" style={{color:T.ink,fontSize:11}}>Verification information</div><div className="f-body mt-1" style={{color:T.ink60,fontSize:10}}>Supply identifiers you have. Missing numbers can be left blank and will be reviewed manually.</div></div><div className="grid grid-cols-2 gap-3"><Field label="COMPANY REG. NO."><input className={input} style={style} value={form.registrationNumber} onChange={e=>update("registrationNumber",e.target.value)} placeholder="Registrar of Companies no."/></Field><Field label="EACZ REGISTRATION NO."><input className={input} style={style} value={form.eaczNumber} onChange={e=>update("eaczNumber",e.target.value)} placeholder="If a real estate agency"/></Field></div><Field label="TAX / ZIMRA NUMBER"><input className={input} style={style} value={form.taxNumber} onChange={e=>update("taxNumber",e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="DIRECTOR ID TYPE"><select className={input} style={style} value={form.directorIdType} onChange={e=>update("directorIdType",e.target.value)}><option>National ID</option><option>Passport</option><option>Driver's Licence</option></select></Field><Field label="DIRECTOR ID NUMBER"><input className={input} style={style} value={form.directorIdNumber} onChange={e=>update("directorIdNumber",e.target.value)}/></Field></div><Field label="PROFILE DESCRIPTION"><textarea rows="4" className={input} style={style} value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Tell clients what makes your company reliable."/></Field></div>}
  {step===4&&<div className="space-y-3"><div className="rounded-2xl p-4" style={{background:T.paperDim}}><div className="flex items-center gap-2"><CheckCircle2 size={17} style={{color:T.msasa}}/><span className="f-display font-semibold" style={{color:T.ink,fontSize:13}}>Final registration checks</span></div><div className="f-body mt-3 space-y-2" style={{color:T.ink60,fontSize:10.5}}><div>✓ Accurate company and representative information</div><div>✓ Correct company type and services selected</div><div>✓ Service areas and operating history supplied</div><div>✓ Verification identifiers supplied where available</div><div>✓ Profile is verified and ready to appear in the app</div></div></div><label className="flex gap-2.5 p-3 rounded-xl" style={{background:T.paperDim}}><input type="checkbox" checked={form.offersValuations} onChange={e=>update("offersValuations",e.target.checked)}/><span className="f-body" style={{fontSize:11,color:T.ink}}>We offer property valuation services.</span></label><label className="flex gap-2.5 p-3 rounded-xl" style={{background:T.paperDim}}><input type="checkbox" checked={form.acceptsListingLeads} onChange={e=>update("acceptsListingLeads",e.target.checked)}/><span className="f-body" style={{fontSize:11,color:T.ink}}>We are available to receive listing and client leads.</span></label><label className="flex gap-2.5 p-3 rounded-xl" style={{background:T.paperDim}}><input type="checkbox" checked={form.agreesTerms} onChange={e=>update("agreesTerms",e.target.checked)}/><span className="f-body" style={{fontSize:11,color:T.ink}}>I confirm that the information supplied is accurate and I agree to ImbaLink's company rules.</span></label></div>}
  {error&&<div className="mt-3 rounded-xl p-3 f-body" style={{background:"rgba(184,61,49,.1)",color:T.brick,fontSize:10.5}}>{error}</div>}
  <div className="flex gap-2 mt-5">{step>1&&<button type="button" onClick={()=>setStep(s=>s-1)} className="px-5 py-3 rounded-full f-body font-semibold" style={{background:T.paperDim,color:T.ink,fontSize:11}}>Back</button>}{step<4?<button type="button" onClick={next} className="flex-1 py-3 rounded-full f-display font-semibold flex justify-center items-center gap-2" style={{background:T.brick,color:T.paper,fontSize:12}}>Continue <ChevronRight size={15}/></button>:<button type="submit" className="flex-1 py-3 rounded-full f-display font-semibold" style={{background:T.brick,color:T.paper,fontSize:12}}>Submit company registration</button>}</div>
 </form></div>;
}
