import { useEffect, useState } from "react";
import { getModerationRecords } from "../../services/admin/adminModeration";
import { StatusBadge } from "../../components/admin/AdminDataTable";
import useAdminRealtime from "../../hooks/useAdminRealtime";

function SimpleTable({ columns, rows }) { return <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r,i)=><tr key={r.id||r.user_id||i}>{columns.map(([key])=><td key={key}>{key==="status"||key==="verification"||key==="verification_status"?<StatusBadge value={r[key]}/>:key==="details"?<span className="admin-cell-muted">{r[key]&&typeof r[key]==="object"?Object.keys(r[key]).slice(0,3).join(", "):"—"}</span>:r[key] ?? "—"}</td>)}</tr>) : <tr><td colSpan={columns.length}><div className="admin-table-state">No records found.</div></td></tr>}</tbody></table></div> }

export default function AdminGenericPage({ type }) {
  const [rows,setRows]=useState([]); const [loading,setLoading]=useState(type==="students"||type==="contractors"); const [error,setError]=useState("");
  const load=()=>{if(!["students","contractors"].includes(type))return;setLoading(true);const store=type==="students"?"student_profiles":"contractors";getModerationRecords(store).then(setRows).catch(e=>setError(e?.message||"Unable to load staff records.")).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[type]);
  useAdminRealtime(()=>load(), { enabled:["students","contractors"].includes(type) });
  const config={students:{title:"Students",desc:"Student verification, university records and demand signals.",columns:[["user_id","User"],["university_id","University"],["verification_status","Verification"],["details","Profile details"],["updated_at","Updated"]]},contractors:{title:"Contractors",desc:"Contractor registrations, trades, service areas and verification.",columns:[["business_name","Business"],["primary_trade","Trade"],["city","City"],["rating","Rating"],["jobs","Jobs"],["verification","Verification"]]},analytics:{title:"Analytics",desc:"Deeper reporting built from the same protected aggregate layer as the main dashboard."},settings:{title:"Administration",desc:"Security controls, staff roles and audit policies remain server-authorized."}}[type]||{title:"Administration",desc:"Staff operations"};
  return <div className="admin-page"><div className="admin-page-title"><div><div className="admin-breadcrumb">Administration <span>/</span> {config.title}</div><h1>{config.title}</h1><p>{config.desc}</p></div></div>{error&&<div className="admin-alert"><span>{error}</span></div>}{["students","contractors"].includes(type)?<section className="admin-panel admin-table-panel"><div className="admin-panel-head"><div><h2>{config.title} directory</h2><p>Staff-only operational records.</p></div></div>{loading?<div className="admin-table-state">Loading…</div>:<SimpleTable columns={config.columns} rows={rows}/>}</section>:<section className="admin-panel admin-placeholder"><div className="admin-placeholder-icon">{type==="settings"?"🔐":"✦"}</div><h2>{type==="settings"?"Secure administration":"Analytics workspace"}</h2><p>{type==="settings"?"Staff roles are read from Supabase Auth app_metadata and privileged changes are protected by server-side RPCs. No service-role credentials are shipped to the browser.":"The main dashboard is the executive overview. This workspace is reserved for additional drill-down reports as the platform's data volume grows."}</p></section>}</div>
}
