import { useEffect, useMemo, useState } from "react";
import { Archive, AlertTriangle, CheckCircle2, ChevronRight, Clock3, Eye, Flag, History, RefreshCw, RotateCcw, Search, ShieldAlert, ShieldCheck, Undo2, XCircle } from "lucide-react";
import { getAdminVerificationQueue, getNeglectedVerifications, neglectVerification, restoreNeglectedVerification } from "../../services/admin/adminModeration";
import { setAdminVerification } from "../../services/admin/adminAnalytics";
import { getVerificationCenterMetrics, getVerificationDecisionHistory } from "../../services/admin/adminVerificationCenter";
import AdminDataTable, { StatusBadge } from "../../components/admin/AdminDataTable";
import useAdminRealtime from "../../hooks/useAdminRealtime";

const STORES=[["all","Everything"],["properties","Properties"],["landlord_verifications","Landlords"],["student_profiles","Students"],["contractors","Contractors"],["registrations","Registrations"]];
const LABELS=Object.fromEntries(STORES.map(x=>x));
const CATS=[["pending","Pending",Clock3],["verified","Verified",CheckCircle2],["flagged","Flagged",Flag],["rejected","Declined",XCircle],["neglected","Neglected",Archive],["history","My record",History]];
const storeFromSubject=t=>({property:"properties",landlord:"landlord_verifications",student:"student_profiles",contractor:"contractors",registration:"registrations"}[t]||"properties");
const storeLabel=s=>LABELS[s]||s;
const title=(r,s)=>r.subject_name||(s==="properties"?r.title:s==="landlord_verifications"?r.landlord_name:s==="student_profiles"?r.student_name:s==="contractors"?r.business_name:r.business_name||r.legal_name)||"Verification record";
const key=(r,s)=>r.record_id||(s==="student_profiles"||s==="landlord_verifications"?r.user_id:r.id);
const date=v=>v?new Date(v).toLocaleString([],{dateStyle:"medium",timeStyle:"short"}):"—";

function Confirm({action,row,store,onCancel,onConfirm,busy}){
 const [note,setNote]=useState(""); if(!action)return null;
 const names={verified:"Verify",pending:"Unverify",flagged:"Flag",rejected:"Decline",neglect:"Neglect",restore:"Restore"};
 const danger=["pending","rejected","neglect"].includes(action);
 const copy={verified:"This publishes an approved trust state.",pending:"This immediately removes the verified state and returns the record to Pending.",flagged:"This marks the record for investigation.",rejected:"This records a declined verification decision.",neglect:"This removes the record from the active queue without deleting it.",restore:"This returns the record to the active queue using its previous status."};
 return <div className="admin-modal-backdrop"><div className="admin-modal verification-confirm-modal"><div className="admin-modal-head"><div><span className="admin-kicker"><ShieldAlert size={13}/> {danger?"Serious administrative action":"Verification decision"}</span><h2>{names[action]} {title(row,store)}</h2><p>{storeLabel(store)} · {row?.email||row?.subject_detail||row?.city||""}</p></div></div><div className={`admin-alert ${danger?"admin-alert-danger":""}`}><AlertTriangle size={17}/><span>{copy[action]} <b>Confirm before saving. This is audited.</b></span></div><label className="admin-form-label">Decision note <textarea autoFocus className="admin-textarea" value={note} onChange={e=>setNote(e.target.value)} placeholder="Reason, evidence or handover note…" maxLength={500}/><small>{note.length}/500</small></label><div className="admin-modal-foot"><button className="admin-button secondary" onClick={onCancel}>Cancel</button><button className="admin-button" disabled={busy} onClick={()=>onConfirm(note)}>{busy?<><RefreshCw size={14} className="admin-spin"/> Saving…</>:<><ShieldCheck size={14}/> Confirm & save</>}</button></div></div></div>;
}

function Drawer({row,store,onClose,onAction}){
 if(!row)return null; const s=row.store_name||store; const st=row.status||row.to_status||row.previous_status;
 return <aside className="verification-drawer"><div className="verification-drawer-head"><div><span className="admin-kicker">Record review</span><h2>{title(row,s)}</h2><p>{storeLabel(s)} · {row.email||row.subject_detail||row.city||""}</p></div><button className="admin-icon-button" onClick={onClose}>×</button></div><div className="verification-drawer-body"><div className="verification-detail-status"><span>Current decision</span><StatusBadge value={st}/></div><div className="verification-detail-grid"><div><small>Type</small><b>{storeLabel(s)}</b></div><div><small>Record ID</small><b className="mono">{key(row,s)}</b></div><div><small>Submitted</small><b>{date(row.created_at||row.submitted_at||row.neglected_at)}</b></div><div><small>Last review</small><b>{date(row.reviewed_at||row.updated_at)}</b></div></div>{row.note&&<div className="verification-note"><small>Admin note</small><p>{row.note}</p></div>}{row.review_note&&<div className="verification-note"><small>Latest review note</small><p>{row.review_note}</p></div>}<div className="verification-drawer-actions">{row.previous_status&&row.restored_at==null?<button className="admin-button" onClick={()=>onAction("restore",row,s)}><RotateCcw size={14}/> Restore</button>:<>{st==="verified"&&<button className="admin-button secondary" onClick={()=>onAction("pending",row,s)}><Undo2 size={14}/> Unverify</button>}{st!=="verified"&&<button className="admin-button" onClick={()=>onAction("verified",row,s)}><CheckCircle2 size={14}/> Verify</button>}{st!=="flagged"&&<button className="admin-button secondary" onClick={()=>onAction("flagged",row,s)}><Flag size={14}/> Flag</button>}{st!=="rejected"&&<button className="admin-button secondary" onClick={()=>onAction("rejected",row,s)}><XCircle size={14}/> Decline</button>}<button className="admin-button secondary" onClick={()=>onAction("neglect",row,s)}><Archive size={14}/> Neglect</button></>}</div></div></aside>;
}

export default function AdminVerificationsPage(){
 const [category,setCategory]=useState("pending"),[store,setStore]=useState("all"),[rows,setRows]=useState([]),[neglected,setNeglected]=useState([]),[history,setHistory]=useState([]),[metrics,setMetrics]=useState({}),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState(null),[action,setAction]=useState(null),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const ss=store==="all"?STORES.slice(1).map(x=>x[0]):[store];const historyStatus=category==="rejected"?"rejected":null;const [m,n,h,a]=await Promise.all([getVerificationCenterMetrics(),getNeglectedVerifications(store==="all"?null:store),getVerificationDecisionHistory({scope:"mine",status:historyStatus,store:store==="all"?null:store,limit:300}),category==="history"||category==="rejected"||category==="neglected"?Promise.resolve([]):Promise.all(ss.map(s=>getAdminVerificationQueue(s,category))).then(x=>x.flat())]);setMetrics(m);setNeglected(n);setHistory(h);setRows(a);}catch(e){setError(e?.message||"Unable to load the Verification Center.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[category,store]);
 useAdminRealtime(()=>load());
 const shown=useMemo(()=>{const b=category==="history"||category==="rejected"?history:category==="neglected"?neglected:rows;const q=query.trim().toLowerCase();return q?b.filter(r=>JSON.stringify(r).toLowerCase().includes(q)):b},[category,history,neglected,rows,query]);
 const act=(kind,row,s)=>setAction({kind,row,store:s||row.store_name||storeFromSubject(row.subject_type)||store});
 const confirm=async note=>{if(!action)return;const {kind,row,store:s}=action;setBusy(true);setError("");try{const id=key(row,s);if(kind==="neglect")await neglectVerification(s,id,note);else if(kind==="restore")await restoreNeglectedVerification(s,id,note);else await setAdminVerification(s,id,kind,note);setAction(null);setSelected(null);await load()}catch(e){setError(e?.message||"The verification decision could not be saved.")}finally{setBusy(false)}};
 const c=n=>Number(metrics?.[n]||0), md=metrics?.my_decisions||{};
 const desc={pending:"New and returning records waiting for an administrator decision.",verified:"Everything carrying an approved trust state. Unverify when evidence changes.",flagged:"Records requiring investigation before they should be trusted.",rejected:"Your declined decisions — a visible operational record you can audit.",neglected:"Parked records that were intentionally removed from the active queue. Nothing is deleted.",history:"Your complete verification decision trail across people, properties and registrations."}[category];
 return <div className="admin-page verification-center-page">
  <section className="verification-command-hero"><div><span className="admin-kicker"><ShieldCheck size={14}/> ImbaLink Trust & Safety</span><h1>Verification Command Center</h1><p>The heart of ImbaLink trust. Every verification decision is live against Supabase and every approval, unverify, decline, flag and neglect action is recorded to the administrator audit trail.</p></div><div className="verification-hero-actions"><div className="verification-live"><span className="verification-live-dot"/> Live database control</div><button className="admin-button secondary" onClick={load}><RefreshCw size={14}/> Refresh</button></div></section>
  {error&&<div className="admin-alert admin-alert-danger"><AlertTriangle size={16}/>{error}</div>}
  <section className="verification-metrics-grid"><button className="verification-metric" onClick={()=>setCategory("pending")}><span><Clock3 size={16}/></span><small>Waiting</small><strong>{c("pending")}</strong><em>Pending now</em></button><button className="verification-metric" onClick={()=>setCategory("verified")}><span><CheckCircle2 size={16}/></span><small>Trusted</small><strong>{c("verified")}</strong><em>Verified now</em></button><button className="verification-metric" onClick={()=>setCategory("rejected")}><span><XCircle size={16}/></span><small>Declined by you</small><strong>{Number(md.declined_decisions||0)}</strong><em>Decision history</em></button><button className="verification-metric" onClick={()=>setCategory("flagged")}><span><Flag size={16}/></span><small>Investigation</small><strong>{c("flagged")}</strong><em>Flagged now</em></button><button className="verification-metric" onClick={()=>setCategory("neglected")}><span><Archive size={16}/></span><small>Parked</small><strong>{c("neglected")}</strong><em>Recoverable</em></button><button className="verification-metric" onClick={()=>setCategory("history")}><span><History size={16}/></span><small>My record</small><strong>{Number(md.total_decisions||0)}</strong><em>{Number(md.decisions_24h||0)} in 24h</em></button></section>
  <section className="verification-record-strip"><div><b>Administrator accountability</b><span>Verification is not just a button — every decision has a record, timestamp and optional reason.</span></div><div className="verification-record-stats"><span><b>{Number(md.verified_decisions||0)}</b> verified</span><span><b>{Number(md.unverify_decisions||0)}</b> unverified</span><span><b>{Number(md.declined_decisions||0)}</b> declined</span><span><b>{Number(md.flagged_decisions||0)}</b> flagged</span></div></section>
  <section className="verification-workspace admin-panel"><div className="verification-workspace-top"><div><span className="admin-kicker">{category==="history"?"Decision history":category==="neglected"?"Recovery vault":"Live verification queue"}</span><h2>{CATS.find(x=>x[0]===category)?.[1]} <span>{shown.length}</span></h2><p>{desc}</p></div><div className="verification-tools"><div className="admin-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, email, city, ID…"/></div><select className="admin-select" value={store} onChange={e=>setStore(e.target.value)}>{STORES.map(([id,l])=><option key={id} value={id}>{l}</option>)}</select></div></div>
   <div className="verification-category-tabs">{CATS.map(([id,l,I])=><button key={id} className={category===id?"is-active":""} onClick={()=>setCategory(id)}><I size={14}/>{l}<b>{id==="pending"?c("pending"):id==="verified"?c("verified"):id==="rejected"?Number(md.declined_decisions||0):id==="flagged"?c("flagged"):id==="neglected"?c("neglected"):Number(md.total_decisions||0)}</b></button>)}</div>
   <AdminDataTable title="" subtitle={loading?"Loading live records…":`${shown.length} records`} loading={loading} total={shown.length} page={0} onPageChange={()=>{}} hidePagination><tr><th>Record</th><th>Type</th><th>Details</th><th>Status / decision</th><th>When</th><th></th></tr>{!loading&&shown.map((r,i)=>{const s=r.store_name||storeFromSubject(r.subject_type)||store;const st=r.status||r.to_status||r.previous_status;return <tr key={`${s}-${key(r,s)}-${r.id||i}`} className="verification-row" onClick={()=>setSelected(r)}><td><div className="verification-record-name"><div>{title(r,s).charAt(0).toUpperCase()}</div><span><b>{title(r,s)}</b><small>{r.email||r.subject_detail||r.city||r.admin_name||""}</small></span></div></td><td><span className="verification-type">{storeLabel(s)}</span></td><td>{category==="history"?<span>{r.from_status?`${r.from_status} → `:""}<b>{r.to_status}</b>{r.note&&<small className="admin-cell-muted">{r.note}</small>}</span>:category==="neglected"?<span>Previously <b>{r.previous_status}</b><small className="admin-cell-muted">By {r.neglected_by_name}</small></span>:<span>{r.property_type||r.university_name||r.primary_trade||r.kind||r.city||"Verification submitted"}</span>}</td><td><StatusBadge value={category==="neglected"?"neglected":category==="history"?r.to_status:st}/>{category==="history"&&<small className="admin-cell-muted">{r.admin_name}</small>}</td><td>{date(r.created_at||r.neglected_at||r.submitted_at)}</td><td><button className="verification-open" onClick={e=>{e.stopPropagation();setSelected(r)}}><Eye size={14}/> Review <ChevronRight size={13}/></button></td></tr>})}</AdminDataTable>
   {!loading&&!shown.length&&<div className="verification-empty"><ShieldCheck size={30}/><h3>No records here</h3><p>This category is live from Supabase and will populate automatically when records enter it.</p></div>}
  </section>
  {selected&&<Drawer row={selected} store={selected.store_name||storeFromSubject(selected.subject_type)||store} onClose={()=>setSelected(null)} onAction={(kind,row,s)=>{if(category==="neglected"&&kind!=="restore")return;act(kind,row,s)}}/>}
  {action&&<Confirm action={action.kind} row={action.row} store={action.store} onCancel={()=>setAction(null)} onConfirm={confirm} busy={busy}/>} 
 </div>;
}
